#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jan 07 14:10:38 CET 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim funcion_cuad_tb_behav -key {Behavioral:sim_1:Functional:funcion_cuad_tb} -tclbatch funcion_cuad_tb.tcl -view /home/matiaspc/Escritorio/universidad/tfg/trabajo final v1.0/funcion_cuad_tb_behav.wcfg -log simulate.log"
xsim funcion_cuad_tb_behav -key {Behavioral:sim_1:Functional:funcion_cuad_tb} -tclbatch funcion_cuad_tb.tcl -view /home/matiaspc/Escritorio/universidad/tfg/trabajo final v1.0/funcion_cuad_tb_behav.wcfg -log simulate.log

