webtalk_init -webtalk_dir /home/matiaspc/Escritorio/universidad/tfg/trabajo/trabajo_final/trabajo_final.sim/sim_1/behav/xsim/xsim.dir/funcion_activacion_tb_avanzado_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr 15 18:57:14 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f87a1bb3-e440-4a3d-9c02-f39d9188132e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1d7e73df8fab4e408e5bee25fd65c24c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "139" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Linuxmint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 20.1" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1407.375 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "15" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "81 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "26 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "712" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "118" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.43_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "286216_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3826743515 -regid "" -xml /home/matiaspc/Escritorio/universidad/tfg/trabajo/trabajo_final/trabajo_final.sim/sim_1/behav/xsim/xsim.dir/funcion_activacion_tb_avanzado_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/matiaspc/Escritorio/universidad/tfg/trabajo/trabajo_final/trabajo_final.sim/sim_1/behav/xsim/xsim.dir/funcion_activacion_tb_avanzado_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/matiaspc/Escritorio/universidad/tfg/trabajo/trabajo_final/trabajo_final.sim/sim_1/behav/xsim/xsim.dir/funcion_activacion_tb_avanzado_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
